apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: frontend-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: frontend-app
